name: responder-config-gts-10-30-2019
namespace: com.citrix.adc.stylebooks
version: "1.0"
display-name: Responder Config StyleBook
private: true
description: This StyleBook contains the different responder configuration that can be applied to traffic by Citrix ADC
schema-version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    version: "11.1"
    prefix: ns
  - 
    namespace: com.citrix.adc.stylebooks
    version: "1.0"
    prefix: stlb
  - 
    namespace: com.citrix.adc.commontypes
    version: "1.0"
    prefix: cmtypes
parameters:
  -
    name: appname
    label: SharePoint Application Name
    description: The Name of this Sharepoint Application
    type: string
    required: true
  - 
    name: lb-virtual-ip
    label: "Load Balanced App Virtual IP address"
    description: "Virtual IP address representing the Load Balanced application"
    type: ipaddress
  - 
    name: lb-virtual-port
    label: "Load Balanced App Virtual Port"
    description: "TCP port representing the Load Balanced application"
    type: tcp-port
    default: 80
  - 
    name: lb-service-type
    label: "Load Balanced App Protocol"
    description: "Protocol used for the Load Balanced application."
    type: string
    default: HTTP  
parameters-default-sources:
    - cmtypes::responder-config-params-gts-10-30-2019
components:
    # -
    #   name: responder-enable-feature-comp
    #   type: ns::nsfeature
    #   description: Enables the RESPONDER feature on Citrix ADC
    #   meta-properties:
    #       action: enable
    #   properties:
    #       feature: ["responder"]
    - 
      name: responder-policy-label-comp
      type: ns::responderpolicylabel
      description: The responder policy label to which all responder policies are bound
      properties: 
        labelname: $parameters.appname + "-responderpolicylabel"
    -
        name: redirect-comp
        type: stlb::redirect-url
        condition: $parameters.responder-config.redirect-urls
        repeat: $parameters.responder-config.redirect-urls
        repeat-item: res
        properties:
            appname: $parameters.appname + str($res.target-expr)
            redirect-url: $res
        components:
          -
            name: responderpolicy-responderpolicylabel-binding-comp
            type: ns::responderpolicylabel_responderpolicy_binding
            description: Binds the responder policy  to the responder policy label
            properties:
              labelname: $components.responder-policy-label-comp.properties.labelname
              policyname: $parent.outputs.redirect-url-policy.properties.name
              gotopriorityexpression: END
              priority: 10
    -
        name: redirect-to-https-lb-comp
        type: ns::lbvserver
        condition: $parameters.lb-virtual-ip and $parameters.responder-config and $parameters.responder-config.redirect-to-https and $parameters.lb-service-type == "SSL"
        properties:
            name: $parameters.appname + "-lb"
            servicetype: upper($parameters.lb-service-type)
            ipv46: $parameters.lb-virtual-ip
            port?: $parameters.lb-virtual-port
            redirectfromport: 80        
outputs:
  -
    name: responder-policy-label
    value: $components.responder-policy-label-comp.properties.labelname



